version: "2"
services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: docker
      ME_CONFIG_MONGODB_ADMINPASSWORD: docker
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: "mongo"
    volumes:
      - ./data/mongo/db:/data/db
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
